version: '3.9'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/code

  db:
    image: postgres:16.0
    environment:
    - POSTGRES_PASSWORD=21511769
    - POSTGRES_USER=postgres
    - POSTGRES_DB=main
    ports:
    - 5432:5432

  